### ISSUE TITLE
get sentiment for selected company(ies)

### ISSUE THREAD

**Issue by aousabdo** [mblitton/GPT-Sentiment-Bot#1]
It would be nice to have the /get_sentiments prompt take a company, or a list of companies as an input, instead of returning the sentiment for all tracked companies

**Comment by mblitton** [comment]
I like this idea. I'll get working on it.

**Comment by mblitton** [comment]
I've added the changes. I changed the original `/get_sentiments` to `/get_list_sentiments`. I added `get_sentiment` which will take a comma-separated list of stock tickers. Example: /get_sentiment AAPL, MSFT, TSLA

**Comment by aousabdo** [comment]
Great. Thank you so much
