### ISSUE TITLE
Keep track of companies added in DB or local file

### ISSUE THREAD

**Issue by aousabdo** [mblitton/GPT-Sentiment-Bot#3]
If I add new companies to the list of companies to track, and then exit the python program, the list is reset to the default which is Apple. it would be nice to have the option to reload the last list of companies after quitting the python program

**Comment by mblitton** [comment]
Are you running it within a docket container or just from the command line?

It has persistence within docker currently. I can update it so it stay locally as well.

**Comment by aousabdo** [comment]
I am following the documentation you had on github, so python main.py. I guess I need to familiarize myself on how to run from the docker container

**Comment by mblitton** [comment]
I wasn't able to reproduce your issue. When I run the program locally on my computer, it saves the list of companies within a JSON file (tickers.json) inside the project folder. Is that file showing up for you?

**Comment by aousabdo** [comment]
Initially it wasn't but now it does. So I guess you can close the issue. Thank you

**Comment by mblitton** [comment]
You're welcome!
