### ISSUE TITLE
API call returns 0 headlines for some companies/Crypto although the URL works in the browser

### ISSUE THREAD

**Issue by aousabdo** [mblitton/GPT-Sentiment-Bot#4]
Whenever I try a ticker such as BTC, ETH, or even some companies such as HUT mining, which exists in EOD DB, the code returns that there are 0 headlines, although the URL in the code, if I take it and paste it in a browser, shows there are headlines, just like AAPL, etc.

**Comment by mblitton** [comment]
I found the issues. HUT is a Canadian company, I don't see any documentation on  EOD for pulling news headlines for Canadian or European stocks (https://eodhistoricaldata.com/financial-apis/stock-market-financial-news-api/)

As for BTC and ETH, the last news updates in the API call are from March 2022, that is why they are retrieving 0 headlines in Bot. It only checks yesterday's news.

**Comment by aousabdo** [comment]
Makes sense, thank you
